messages:
  no-permission: "&cYou do not have permission to use this."
  invalid-command: "&cInvalid command."
  extractor-received: "&aYou have received an extractor."
  convert-success: "&aYou have converted your item into an extractor."
  convert-fail: "&cThis item is already an extractor."
  invalid-number: "&cPlease enter a valid number."
  set-uses-success: "&aUses set to %amount%."
  set-uses-fail: "&cThis is not an extractor."
  must-hold-pickaxe: "&cYou must be holding a pickaxe."
